# Generated by Django 3.0.8 on 2020-07-12 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('posts', '0005_auto_20200712_1632'),
        ('admin', '0004_auto_20200712_1632'),
        ('users', '0003_auto_20200712_1632'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
